swagger: '2.0'
info:
  title: Argent Bank Transactions API documentation
  description: Proposition d'API pour les transactions
  version: '0.0.1'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v2
schemes:
  - http

# ------------------------------------------------------------------------------

paths:
  /user/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Obtenir toutes les transactions de l'utilisateur pour le mois en cours
      description: API pour récupérer toutes les transactions de l'utilisateur pour le mois en cours, groupées par compte
      parameters:
        - name: month
          in: query
          description: Mois pour lequel récupérer les transactions (format : MM/YYYY)
          required: true
          type: string
      responses:
        '200':
          description: Transactions récupérées avec succès
          schema:
            type: array
            items:
              $ref: '#/definitions/Transaction'
        '400':
          description: Mois invalide
        '500':
          description: Erreur interne du serveur

  /user/transactions/{transaction_id}:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Obtenir les détails d'une transaction d'utilisateur
      description: API pour récupérer les détails d'une transaction d'utilisateur
      parameters:
        - name: transaction_id
          in: path
          description: ID de la transaction à récupérer
          required: true
          type: string
      responses:
        '200':
          description: Détails de la transaction récupérés avec succès
          schema:
            $ref: '#/definitions/Transaction'
        '404':
          description: Transaction non trouvée
        '500':
          description: Erreur interne du serveur

    put:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Mettre à jour une transaction d'utilisateur
      description: API pour mettre à jour une transaction d'utilisateur
      parameters:
        - in: body
          name: body
          description: Données de la transaction à mettre à jour
          required: true
          schema:
            $ref: '#/definitions/Transaction'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction mise à jour avec succès
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Données de transaction invalides
        '404':
          description: Transaction non trouvée
        '500':
          description: Erreur interne du serveur

# ------------------------------------------------------------------------------

definitions:
  Transaction:
    type: object
    properties:
      id:
        type: string
        description: Identifiant unique de la transaction
      accountId:
        type: string
        description: Identifiant du compte associé à la transaction
      amount:
        type: number
        description: Montant de la transaction
      description:
        type: string
        description: Description de la transaction
      date:
        type: string
        format: date
        description: Date de la transaction
      category:
        type: string
        description: Catégorie de la transaction
